# Fundamentals of Tensor Operations using PyTorch and NumPy

This notebook demonstrates basic tensor operations using both **PyTorch** and **NumPy**.

In [1]:
import torch
import numpy as np


## 1. Creating 1D, 2D, and 3D Tensors

In [2]:
# PyTorch
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([[1, 2], [3, 4]])
t3 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# NumPy
n1 = np.array([1, 2, 3])
n2 = np.array([[1, 2], [3, 4]])
n3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("PyTorch Tensors:", t1, t2, t3, sep="\n")
print("\nNumPy Arrays:", n1, n2, n3, sep="\n")

PyTorch Tensors:
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

NumPy Arrays:
[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 2. Element-wise Addition, Subtraction, Multiplication, and Division

In [3]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

# NumPy
na = np.array([1.0, 2.0, 3.0])
nb = np.array([4.0, 5.0, 6.0])

print("\nNumPy Addition:", na + nb)
print("NumPy Subtraction:", na - nb)
print("NumPy Multiplication:", na * nb)
print("NumPy Division:", na / nb)

Addition: tensor([5., 7., 9.])
Subtraction: tensor([-3., -3., -3.])
Multiplication: tensor([ 4., 10., 18.])
Division: tensor([0.2500, 0.4000, 0.5000])

NumPy Addition: [5. 7. 9.]
NumPy Subtraction: [-3. -3. -3.]
NumPy Multiplication: [ 4. 10. 18.]
NumPy Division: [0.25 0.4  0.5 ]


## 3. Dot Product and Matrix Multiplication

In [4]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

print("Matrix Multiplication:", torch.matmul(x, y))
print("Dot Product (flattened):", torch.dot(torch.flatten(x), torch.flatten(y)))

# NumPy
nx = np.array([[1, 2], [3, 4]])
ny = np.array([[5, 6], [7, 8]])

print("\nNumPy Matrix Multiplication:", np.matmul(nx, ny))
print("NumPy Dot Product (flattened):", np.dot(nx.flatten(), ny.flatten()))

Matrix Multiplication: tensor([[19, 22],
        [43, 50]])
Dot Product (flattened): tensor(70)

NumPy Matrix Multiplication: [[19 22]
 [43 50]]
NumPy Dot Product (flattened): 70


## 4. Indexing and Slicing

In [5]:

t = torch.tensor([[10, 20, 30], [40, 50, 60]])
print("Original Tensor:", t)
print("First row:", t[0])
print("Element at (1,2):", t[1,2])
print("Boolean Masking:", t[t > 30])

# NumPy
nt = np.array([[10, 20, 30], [40, 50, 60]])
print("\nNumPy Boolean Masking:", nt[nt > 30])


Original Tensor: tensor([[10, 20, 30],
        [40, 50, 60]])
First row: tensor([10, 20, 30])
Element at (1,2): tensor(60)
Boolean Masking: tensor([40, 50, 60])

NumPy Boolean Masking: [40 50 60]


## 5. Reshaping: view(), reshape(), unsqueeze(), and squeeze() in PyTorch vs NumPy reshape

In [6]:
p = torch.tensor([[1, 2], [3, 4], [5, 6]])

print("View:", p.view(2, 3))
print("Reshape:", p.reshape(2, 3))
print("Unsqueeze (add dim at 0):", p.unsqueeze(0))
print("Squeeze (remove dim):", p.unsqueeze(0).squeeze())

# NumPy reshape
np_arr = np.array([[1, 2], [3, 4], [5, 6]])
print("\nNumPy Reshape:", np_arr.reshape(2, 3))

View: tensor([[1, 2, 3],
        [4, 5, 6]])
Reshape: tensor([[1, 2, 3],
        [4, 5, 6]])
Unsqueeze (add dim at 0): tensor([[[1, 2],
         [3, 4],
         [5, 6]]])
Squeeze (remove dim): tensor([[1, 2],
        [3, 4],
        [5, 6]])

NumPy Reshape: [[1 2 3]
 [4 5 6]]


## 6. Broadcasting

In [7]:
a = torch.tensor([[1], [2], [3]])
b = torch.tensor([10, 20, 30])
print("Broadcasted addition:", a + b)

# NumPy
na = np.array([[1], [2], [3]])
nb = np.array([10, 20, 30])
print("NumPy Broadcasted addition:", na + nb)


Broadcasted addition: tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])
NumPy Broadcasted addition: [[11 21 31]
 [12 22 32]
 [13 23 33]]


## 7. In-place vs Out-of-place Operations

In [8]:
a = torch.tensor([1.0, 2.0, 3.0])
b = a.clone()

# Out-of-place
c = a + 1
print("Original a:", a)
print("Out-of-place a + 1:", c)

# In-place (modifies a)
a.add_(1)
print("In-place a.add_(1):", a)

Original a: tensor([1., 2., 3.])
Out-of-place a + 1: tensor([2., 3., 4.])
In-place a.add_(1): tensor([2., 3., 4.])
